version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEPTH"
leavesCullingAmount = 1
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
mcwfences = true
pmweather = true
mcwroofs = true
mcwwindows = true
mcwstairs = true
connectedglass = true
mcwbiomesoplenty = true
cataclysm = true
lolmfv = true
aether_enhanced_extinguishing = true
lolmbv = true
irons_spellbooks = true
magic_mirror = true
dramaticdoors = true
ironbookshelves = true
mcwpaths = true
woodwevegot = true
mld = true
mcwbridges = true
aether = true
mcwlights = true
mcwtrpdoors = true
mcwholidays = true
snowrealmagic = true
lolmct = true
lolmcv = true
livingthings = true
biomesoplenty = true
sophisticatedbackpacks = true
waterframes = true
exposure = true
workshop_for_handsome_adventurer = true
mcwdoors = true
notenoughpots = true
aether_ores = true
chipped = true
vampirism = true
bno = true
deep_aether = true
sereneseasons = true
biomeswevegone = true
visualworkbench = true
elixirum = true
minecraft = true
mcwfurnitures = true
expanded_combat = true
multibeds = true
sophisticatedstorage = true
bosses_of_mass_destruction = true
ars_elemental = true
waystones = true
monolib = true
ars_nouveau = true
chisel_chipped_integration = true
rechiseled = true
disenchanting_table = true
