#Whether radar blocks require a completed WSR-88D to be nearby for display
requirewsr88d = false
#Range within which clouds and storms will spawn from players
# Default: 384
# Range: 256 ~ 2048
spawnrange = 384
#1 in x chance that a spawning storm will spawn as a squall
# Default: 10
# Range: 1 ~ 100
chanceinonesquall = 10
#1 in x chance that a storm will progress to stage 1
# Default: 2
# Range: 1 ~ 100
chanceinonestage1 = 2
#1 in x chance that a storm will progress to stage 2
# Default: 3
# Range: 1 ~ 100
chanceinonestage2 = 3
#1 in x chance that a storm will progress to stage 3 / tornado
# Default: 5
# Range: 1 ~ 100
chanceinonestage3 = 5
#Risk curve, higher is rarer
# Default: 1.0
# Range: 0.5 ~ 2.0
riskcurve = 1.0
#Multiplier of squall windspeeds
# Default: 1.25
# Range: 0.0 ~ 2.0
squallstrengthmultiplier = 1.25
#Chance a storm will spawn each minute
# Default: 0.2
# Range: 0.0 ~ 1.0
stormspawnchanceperminute = 0.2
#Whether chance to spawn storms and chance for storms to progress is affected by the game environment
environmentsystem = true
#Maximum number of active storms allowed to spawn
# Default: 5
# Range: 1 ~ 10
maxstorms = 5
#Maximum precipitation accumulation, 0 = off
# Default: 6
# Range: 0 ~ 8
snowaccumulationheight = 6
#List of blocks and respective windspeed at which they get damaged
blockstrengths = ["minecraft:acacia_leaves=55", "minecraft:azalea_leaves=55", "minecraft:birch_leaves=50", "minecraft:dark_oak_leaves=55", "minecraft:cherry_leaves=55", "minecraft:flowering_azalea_leaves=55", "minecraft:mangrove_leaves=65", "minecraft:oak_leaves=55", "minecraft:jungle_leaves=55", "minecraft:chain=75", "minecraft:lantern=75", "minecraft:soul_lantern=75", "minecraft:white_wool=60", "minecraft:orange_wool=60", "minecraft:magenta_wool=60", "minecraft:light_blue_wool=60", "minecraft:yellow_wool=60", "minecraft:lime_wool=60", "minecraft:pink_wool=60", "minecraft:gray_wool=60", "minecraft:light_gray_wool=60", "minecraft:cyan_wool=60", "minecraft:purple_wool=60", "minecraft:blue_wool=60", "minecraft:brown_wool=60", "minecraft:green_wool=60", "minecraft:red_wool=60", "minecraft:black_wool=60"]
#List of blocks not allowed to be damaged
blacklistedblocks = ["minecraft:gravel", "minecraft:farmland", "minecraft:dirt_path"]
#List of blocktags not allowed to be damaged
blacklistedblocktags = ["minecraft:dirt", "minecraft:base_stone_overworld", "minecraft:terracotta", "minecraft:badlands_terracotta", "minecraft:ice", "minecraft:sand"]
#List of valid dimensions for spawning weather
validdimensions = ["minecraft:overworld"]
#Size of storms
# Default: 300.0
# Range: 128.0 ~ 512.0
stormsize = 300.0
#Overcast Modifier
# Default: 0.75
# Range: 0.0 ~ 2.0
overcastpercent = 0.75
#Rain Modifier
# Default: 0.8
# Range: 0.0 ~ 2.0
rainstrength = 0.8
#Height of first cloud layer
# Default: 315.0
# Range: 150.0 ~ 450.0
layer0height = 315.0
#Height of cirrus cloud layer
# Default: 2000.0
# Range: 1000.0 ~ 3000.0
layerCheight = 2000.0
#Maximum width of tornadoes
# Default: 225
# Range: 100 ~ 800
maxtornadowidth = 225
#Whether storms will aim at the player whenever strengthening into a tornado
aimatplayer = false
#Random range of blocks that storms will aim at around players
# Default: 248.0
# Range: 0.0 ~ 1024.0
aimatplayeroffset = 248.0
#Maximum number of blocks allowed to be damaged by a tornado per tick
# Default: 12500
# Range: 5000 ~ 40000
maxblocksdamagedpertick = 12500
#Whether debarking will be applied to logs
dodebarking = true
