mode = "fastest"

[light_sources]
	water_sensitive_check = false
	block_entities = false
	entities = true
	self = true
	tnt = "simple"
	creeper = "simple"

			[light_sources.settings.entities.minecraft]
				zombie_horse = false
				axolotl = false
				zoglin = false
				egg = false
				spawner_minecart = false
				allay = false
				llama = false
				mule = false
				bat = false
				husk = false
				experience_bottle = false
				camel = false
				rabbit = false
				firework_rocket = false
				silverfish = false
				giant = false
				drowned = false
				item = true
				goat = false
				horse = false
				vindicator = false
				minecart = false
				spectral_arrow = false
				llama_spit = false
				mooshroom = false
				glow_item_frame = false
				snowball = false
				tnt = false
				parrot = false
				creeper = true
				lightning_bolt = false
				tadpole = false
				ravager = false
				evoker_fangs = false
				chest_minecart = false
				tropical_fish = false
				slime = false
				pillager = false
				area_effect_cloud = false
				blaze = false
				piglin = false
				endermite = false
				end_crystal = false
				ender_pearl = false
				zombie = false
				item_display = false
				breeze_wind_charge = false
				guardian = false
				fireball = false
				illusioner = false
				eye_of_ender = false
				wither_skull = false
				wolf = false
				block_display = false
				tnt_minecart = false
				zombie_villager = false
				elder_guardian = false
				chest_boat = false
				boat = false
				small_fireball = false
				strider = false
				cave_spider = false
				cod = false
				snow_golem = false
				witch = false
				spider = false
				command_block_minecart = false
				panda = false
				bee = false
				arrow = false
				cow = false
				magma_cube = false
				pig = false
				skeleton = false
				frog = false
				hoglin = false
				armadillo = false
				armor_stand = false
				experience_orb = false
				dolphin = false
				stray = false
				shulker = false
				turtle = false
				salmon = false
				vex = false
				wandering_trader = false
				wither_skeleton = false
				piglin_brute = false
				breeze = false
				ocelot = false
				furnace_minecart = false
				item_frame = false
				phantom = false
				ender_dragon = false
				leash_knot = false
				evoker = false
				marker = false
				glow_squid = false
				warden = false
				shulker_bullet = false
				squid = false
				enderman = false
				dragon_fireball = false
				chicken = false
				sniffer = false
				trader_llama = false
				donkey = false
				bogged = false
				fox = false
				iron_golem = false
				zombified_piglin = false
				cat = false
				wind_charge = false
				ghast = false
				sheep = false
				player = true
				pufferfish = false
				potion = false
				trident = false
				villager = false
				ominous_item_spawner = false
				skeleton_horse = false
				fishing_bobber = false
				text_display = false
				polar_bear = false
				hopper_minecart = false
				falling_block = false
				painting = false
				interaction = false
				wither = false

			[light_sources.settings.block_entities.minecraft]
				bed = true
				calibrated_sculk_sensor = true
				furnace = true
				dropper = true
				daylight_detector = true
				sign = true
				jukebox = true
				brewing_stand = true
				sculk_sensor = true
				hanging_sign = true
				brushable_block = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				crafter = true
				skull = true
				trial_spawner = true
				campfire = true
				vault = true
				barrel = true
				chest = true
				piston = true
				sculk_shrieker = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				sculk_catalyst = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				chiseled_bookshelf = true
				trapped_chest = true
				decorated_pot = true
				blast_furnace = true
