["Tab in creative inventory"]
	#How many wood sets are needed for this mod to use a second tab in creative mode for dynamically created blocks. Set to a high number to disable second tab and shove everything into first.
	# Default: 8
	# Range: 0 ~ 1000
	"Minimum number of sets for separate creative_tab" = 8

["Texture paths"]
	#No reason to disable this. If you do, you need to set texture paths like in this file. While this is enabled, settings below that are texture paths are unused and unneeded.
	"Disable autosearching for textures" = false

	["Texture paths"."Texture paths - manual, if autosearching is disabled"]
		#For wood types that do not have stripped logs, you can specify table top block here. If you do not, we are skipping that wood type.
		"Stripped log substitution list for textures" = "embur=embur, sythian=sythian, bamboo=stripped_bamboo_block, bulbis=bulbis"
		#Tells us where to find plank textures, in case mod uses subdirectories (like byg) or different file names. Second %s below is the wood type. Separate using commas.
		"Texture template1 list" = "biomeswevegone=%s:block/%s/planks, aether=%s:block/construction/%s_planks"
		#Tells us where to find stripped log textures, in case mod uses subdirectories (like byg) or different file names. Second %s below is the wood type. Separate using commas.
		"Texture template2 list" = "biomeswevegone=%s:block/%s/stripped_log,  aether=%s:block/natural/stripped_%s_log"
		#Slightly different model. Do not worry about this. Or just list dark woods here.
		"Use darker workstation model" = "embur,hellbark,bulbis,cika,lament,dead,blackwood"

	["Texture paths"."Autosearching method"]
		#Use the DAG mod to obtain models and textures. There is a backup system, clearly, but DAG should work for cases when this mods resources are overridden by resource packs. Game loading speed may vary.
		"Use Dynamic Asset Generator" = false
